### ISSUE TITLE
Sign In stopped working

### ISSUE THREAD

**Issue by elizabethjmz** [veritosvb/Tortilla-Tracker#16]
**Description:** At sign in process, nothing happens.

**Steps to reproduce:**

1. Click on **SIGN IN** button
2. Enter **Email**
3. Enter **Password**
4. Click **LOG IN** button

**Expected:** Sign in hyperlink from navigation bar should be replaced with "Sign In as: user@email.com"

**Actual:** Sign in is replaced with "Sign Out" button.

Additional information: Probably need to remove Sign Out extra button from navigation bar.

**Comment by veritosvb** [comment]
Resolved. We double up several Id names. We had some

**Comment by elizabethjmz** [comment]
Issue has been fixed by changing the name of the IDs from each form in the HTML so they are unique.

**Comment by avilano** [comment]
Great bug documentation 👍
